version: "3"
services:
  web:
    container_name: web
    image: flask-barn:3
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: 
      - .env
    ports:
      - "32000:3306"
